default_platform(:ios)

TMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TMP_KEYCHAN_PASSWORD_DEFAULT = "tmppassword"
APP_ID = ENV['FIREBASE_IOS_APPID']
BUILD_NUMBER = ENV['GITHUB_RUN_NUMBER']
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']
GITHUB_BRANCH = ENV['GITHUB_REF']

def delete_tmp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_tmp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

def ensure_tmp_keychain(name, password)
  delete_tmp_keychain(name)
  create_tmp_keychain(name, password)
end

platform :ios do
  desc "Build & sign iOS app"
  lane :setup_match do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: "8CW7HSL79U",
      profile_name: "match AdHoc com.sentrei.sentrei.beta",
      code_sign_identity: "iPhone Distribution"
    )
    ensure_tmp_keychain(TMP_KEYCHAIN_NAME_DEFAULT, TMP_KEYCHAN_PASSWORD_DEFAULT)
    match(
      app_identifier: "com.sentrei.sentrei.beta",
      type: "adhoc",
      readonly: is_ci,
      keychain_name: TMP_KEYCHAIN_NAME_DEFAULT,
      keychain_password: TMP_KEYCHAN_PASSWORD_DEFAULT,
      git_url: "https://github.com/shunkakinoki/ios-certificates.git",
      git_basic_authorization: Base64.strict_encode64("shunkakinoki:#{ENV['GITHUB_ACCESS_TOKEN']}")
    )
  end

  desc "Submit a new beta build to firebase"
  lane :beta do
    add_badge(
          dark: true,
          shield: "Version-3-blue",
      )
    setup_match()
    sh("cd ../.. && pwd && flutter build ios --no-codesign  --release --flavor beta")
    firebase_app_distribution(
          app: APP_ID,
          groups: "beta",
          release_notes: BUILD_NUMBER,
          firebase_cli_path: FIREBASE_PATH,
          firebase_cli_token: FIREBASE_TOKEN,
          apk_path: "./build/Runner/sentrei master.ipa"
      )
    delete_tmp_keychain(TMP_KEYCHAIN_NAME_DEFAULT)
  end
end
