default_platform(:ios)

# Default temporary keychain password and name, if not included from environment
TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter" || ENV['TEMP_KEYCHAIN_NAME']
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword" || ENV['TEMP_KEYCHAIN_PASSWORD']
APP_ID = ENV['FIREBASE_IOS_APPID']
BUILD_NUMBER = ENV['GITHUB_RUN_NUMBER']
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']
GITHUB_BRANCH = ENV['GITHUB_REF']

# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_app do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AdHoc #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "adhoc",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "https://github.com/shunkakinoki/ios-certificates.git"
    )
    build_ios_app(
      export_options: {
          method: "ad-hoc"
      },
      output_directory: "./build/Runner"
    )
    delete_temp_keychain(keychain_name)
  end

  desc "Submit a new beta build to firebase"
  lane :beta do
    build_app()
    firebase_app_distribution(
          app: APP_ID,
          groups: "beta",
          release_notes: BUILD_NUMBER,
          firebase_cli_path: FIREBASE_PATH,
          firebase_cli_token: FIREBASE_TOKEN,
          apk_path: "./build/Runner/Runner.ipa"
      )
  end
end
