fastlane_version "2.28.3"

default_platform :android

platform :android do
  desc "Generate android appicons"
  lane :appicon do
    android_appicon(appicon_image_file: 'spec/fixtures/Themoji.png',
    appicon_devices: [:phone, :tablet],
    appicon_path: 'app/res/mipmap')
  end

  desc "Submit a new beta build to firebase"
  lane :beta do
      version = android_get_version_code(
      gradle_file: "app/build.gradle"
      )
      add_badge(
            dark: true,
            shield: "Version-#{version}-blue",
            glob: "/app/src/main/res/mipmap-*/ic_launcher*.png",
      )
      sh("cd ../.. && pwd && flutter build apk --flavor beta")
      firebase_app_distribution(
            groups: "beta",
            app: "1:258612152633:android:0344f8ed2ff95c50ff40e8",
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
            release_notes: ENV['GITHUB_RUN_NUMBER'],
            apk_path: "../build/app/outputs/apk/beta/release/app-beta-release.apk"
      )
  end

  desc "Submit a new master build to firebase"
  lane :master do
      sh("cd ../.. && pwd && flutter build apk --flavor master")
      firebase_app_distribution(
            groups: "master",
            app: "1:721847679884:android:1935b57831163cda5bb4a9",
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
            release_notes: ENV['GITHUB_RUN_NUMBER'],
            apk_path: "../build/app/outputs/apk/master/release/app-master-release.apk"
      )
  end
end
