fastlane_version "2.28.3"

default_platform :android

APP_ID = ENV['FIREBASE_ANDROID_APPID']
BUILD_NUMBER = ENV['GITHUB_RUN_NUMBER']
FIREBASE_PATH = ENV['FIREBASE_PATH']
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']
GITHUB_BRANCH = ENV['GITHUB_REF']

platform :android do
  desc "Submit a new beta build to firebase"
  lane :beta do
    firebase_app_distribution(
          app: APP_ID,
          groups: "beta",
          release_notes: BUILD_NUMBER,
          firebase_cli_path: FIREBASE_PATH,
          firebase_cli_token: FIREBASE_TOKEN,
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end
